#!/bin/sh

#Esse programa tem por finalidade criar uma rede ad hoc entre 2 ou mais computadores

#esse código desativa a busca por redes
service network-manager stop

echo "Informe a sua placa de rede: (wlan0, wlan1,...)"
read placa

#esse codigo torna a interface desativada
ip link set $placa down

#Aqui termina a preparação para a configuração da rede.
#Vamos começar a configurar

#precisamos colocar a rede como modo ad hoc
iwconfig $placa mode ad-hoc

echo "Informe o nome da rede"
read nome
iwconfig $placa essid $nome

echo "Informe o canal"
read canal

iwconfig $placa channel $canal

iwconfig $placa key off

#Terminamos a configuração. Falta ativar a rede:

#Precisamos tornar a interface ativada:
ip link set $placa up

#escolhendo um ip para o computador:

echo "Informe o IP a ser usado:"
read ip

echo "Informe a máscara de rede"
read mask

ip addr add $ip/$mask dev $placa

#Pronto! A rede foi configurada

#Vamos adicionar o gateway padrao para o forward.
echo "Informe o gateway padrão"
read gateway

route add default gw $gateway

#Pronto!!












